// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vizyxxwqknmocaisndpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpenl4eHdxa25tb2NhaXNuZHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMTI5ODMsImV4cCI6MjA3NDc4ODk4M30.tX6kH-hqvEyG-ZuuhhTMF5PcB4nmr0aCJ40UVmjHpG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});